name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Unity
        uses: game-ci/unity-builder@v2
        with:
          unityVersion: 2021.3.0f1

      - name: Build Project
        uses: game-ci/unity-builder@v2
        with:
          targetPlatform: StandaloneWindows64
          unityVersion: 2021.3.0f1

      - name: Test Project
        uses: game-ci/unity-test-runner@v2
        with:
          unityVersion: 2021.3.0f1

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Unity
        uses: game-ci/unity-test-runner@v2
        with:
          unityVersion: 2021.3.0f1

      - name: Run Unit Tests
        uses: game-ci/unity-test-runner@v2
        with:
          testMode: playmode
          unityVersion: 2021.3.0f1
